#! /usr/bin/env bash
shopt -s extglob
#REgex

function Welcome() {
    echo "Welcome To our DataBase Project"
    if [ -e ~/DBMS-Bash-Project/DataBase ] && [ -d ~/DBMS-Bash-Project/DataBase ]; then
        echo "DBMS is Ready"
        cd ~/DBMS-Bash-Project/DataBase 2>>/dev/null
    elif [ -e ~/DBMS-Bash-Project/DataBase ] && [[ -f ~/DBMS-Bash-Project/DataBase ]]; then
        rm ~/DBMS-Bash-Project/DataBase
        mkdir ~/DBMS-Bash-Project/DataBase
        echo "DBMS is now Ready"

    else
        mkdir ~/DBMS-Bash-Project/DataBase
        echo 'DBMS has Been Created'
    fi
}
Welcome
function mainMenu() {
    exit=true

    while $exit; do
        echo "Main Menu:"
        # cd ~/DBMS/DataBase
        select option in "CreateDB" "ListDB" "ConnectDB" "DropDB" "test" "Exit"; do
            case $REPLY in
            "CreateDB" | "1")
                . ~/DBMS/Scripts/createDB.sh
                break
                ;;
            [Ll][Ii][Ss][Tt][Dd][Bb] | "2")
                . ~/DBMS-Bash-Project/Scripts/listDB.sh
                # echo "Existing DataBase:\n$(ls ~/DBMS-Bash-Project/DataBase/)"
                break
                ;;
            "ConnectDB" | "3")
                . ~/DBMS/Scripts/connectDB.sh
                break
                ;;
            [Dd][Rr][Oo][Pp][Dd][Bb] | "4")
                bash ~/DBMS-Bash-Project/Scripts/dropDB.sh

                break
                ;;
            "test" | "5")
                echo "Script  program."
                bash ~/DBMS/Scripts/test.sh
                . ~/DBMS/Scripts/test.sh
                . ~/DBMS/Scripts/./test2
                . ~/DBMS/Scripts/./test.sh
                bash ~/DBMS/Scripts/./test2
                ;;
            "Exit" | "6")
                echo "Exiting program."
                exit 0
                ;;
            *)
                echo "Invalid option. Please try again."
                break
                ;;
            esac
        done

    done
}

mainMenu
