#! /usr/bin/env bash
shopt -s extglob
#REgex
function Welcome() {
    locate=~/DBMS-Bash-Project
    echo "Welcome To our DataBase Project"
    if [ -e ~/DBMS-Bash-Project/DataBase ] && [ -d ~/DBMS-Bash-Project/DataBase ]; then
        echo "DBMS is Ready"
        cd ~/DBMS-Bash-Project/DataBase 2>>/dev/null || exit
    elif [ -e ~/DBMS-Bash-Project/DataBase ] && [[ -f ~/DBMS-Bash-Project/DataBase ]]; then
        rm ~/DBMS-Bash-Project/DataBase
        mkdir ~/DBMS-Bash-Project/DataBase
        echo "DBMS is now Ready"

    else
        mkdir ~/DBMS-Bash-Project/DataBase
        echo 'DBMS has Been Created'
    fi
}
Welcome
function mainMenu() {
    loop=true
    # PS1="SelectOption$"
    while $loop; do
        echo "Main Menu:"
        PS3="SelectOption: "
        # cd ~/DBMS-Bash-Project/DataBase
        select option in CreateDB ListDB ConnectDB DropDB Exit; do
            PS3="SelectOption: "
            case $option in

            [Cc][Rr][Ee][Aa][Tt][Ee][Dd][Bb] | "1")
                . ~/DBMS-Bash-Project/Scripts/createDB.sh
                break
                ;;
            [Ll][Ii][Ss][Tt][Dd][Bb] | "2")
                . ~/DBMS-Bash-Project/Scripts/listDB.sh
                # echo "Existing DataBase:\n$(ls ~/DBMS-Bash-Project/DataBase/)"
                break
                ;;
            [Cc][Oo][Nn][Nn][Ee][Cc][Tt][Dd][Bb] | "3")
                . ~/DBMS-Bash-Project/Scripts/connectDB.sh
                break
                ;;
            [Dd][Rr][Oo][Pp][Dd][Bb] | "4")
                bash ~/DBMS-Bash-Project/Scripts/dropDB.sh

                break
                ;;
            [Ee][Xx][Ii][Tt] | "5")
                echo "Exiting program."
                exit 0
                ;;
            *)
                echo "Invalid option. Please try again."
                break
                ;;
            esac
        done
    done
}

mainMenu
